services: 
  dev_backend:
    container_name: korobasy_backend
    build:
      dockerfile: dev_backend.dockerfile
      context: .
    environment:
      - DEBUG=true
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver
    restart: always
    depends_on:
      - dev_frontend
    working_dir: /app/
    volumes:
      - .:/app:delegated
    ports:
      - "8000:8000"

  dev_frontend:
    build:
      dockerfile: dev_frontend.dockerfile
      context: .
    environment:
      - CI=true
    command: npm start
    restart: always
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - "3000:3000"