# Generated by Django 3.1.2 on 2020-10-29 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='storage',
            name='users',
            field=models.ManyToManyField(through='storages.UserPermission', to='users.User'),
        ),
        migrations.AddField(
            model_name='section',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.storage'),
        ),
    ]
