# Generated by Django 3.1.2 on 2020-10-29 00:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThingInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.section')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.thing')),
            ],
        ),
    ]
